version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Prueba123*
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    container_name: SqlServer

volumes:
  sql-data:
